cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'openssl'
brew 'ruby-build'
brew 'rbenv'
brew 'unrar'
brew 'youtube-dl'
brew 'spark'
brew 'postgres'
brew 'mysql'
brew 'n'
brew 'zsh'
brew 'zsh-syntax-highlighting'

cask '1password'
cask 'google-chrome'
cask 'slack'
cask 'vlc'
cask 'emacs'